---
apiVersion: v1
kind: Namespace
metadata:
  name: cloner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloner
  namespace: cloner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloner-role
  namespace: cloner
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - get
      - create
      - list
      - delete
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - list
      - delete
      - update
  - apiGroups:
      - v1
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloner
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - watch
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloner-rolebinding
  namespace: cloner
subjects:
  - kind: ServiceAccount
    name: cloner
    namespace: cloner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloner-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloner
subjects:
  - kind: ServiceAccount
    name: cloner
    namespace: cloner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloner
---
