apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-1
        image: busybox:1.33.0
        command: ['sh', '-c', 'echo Init Container executing!']
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
